- hosts: 127.0.0.1 # all | testepunk  | "{{ tenant }}"
  connection: local

  tasks:
  - ec2:
      key_name: camidevops
      region: us-east-2
      instance_type: t2.micro
      image: ami-026dea5602e368e96
      wait: yes
      count: 1
      group: default
      instance_tags:
        Name: "{{nameinvault}} "
      monitoring: yes
      termination_protection: no
      assign_public_ip: yes
      vpc_subnet_id: subnet-0ca60f40
    register: deviceidlaunch

  - name: allocate a new elastic IP and associate it with an instance
    ec2_eip:
      device_id: "{{ deviceidlaunch.instance_ids[0] }}" #"{{ item }}"
      region: us-east-2
    #loop: "{{ deviceidlaunch.instance_ids }}"
    register: elasticip

  - name: output the IP
    debug:
      msg: "Allocated IP inside a VPC is {{ elasticip.public_ip }}"

  - name: example using security group rule descriptions
    ec2_group:
      name: "default"
      description: default VPC security group
      vpc_id: vpc-c73adaac
      profile: "default"
      region: us-east-2
      purge_rules: no
      rules:
        - proto: tcp
          ports:
          - 22
          cidr_ip: "{{ elasticip.public_ip }}/32"
          rule_desc: "{{nameinvault}}"

  - name: wait until it's ready
    wait_for:
      timeout: 60

  - name: Cat hosts
    command: cat /etc/ansible/hosts
    register: hostsfileansible

  - name: Add a line to ansible hosts
    lineinfile:
      path: /etc/ansible/hosts
      line: "[{{nameinvault}}]\n{{elasticip.public_ip}}\tansible_ssh_private_key_file=/home/ec2-user/camidevops.pem"
      create: yes
    become: yes
    become_user: root
    when: '"{{nameinvault}}" not in hostsfileansible.stdout' #comentar o verbose

  - name: run playbook
    command: ansible-playbook playbook-inicial.yml --extra-vars="nameinvault={{nameinvault}}"
